### PR TITLE
Add PWMOutputDevice.pulse method

### PR DESCRIPTION
**Pull request by lurch**
...which simply calls blink with different default arguments

### CODE REVIEW

**Comment by lurch** [comment]
This may seem a bit trivial, but it means you can just do:
```python
from gpiozero import PWMLED
from signal import pause

led = PWMLED(21)
led.pulse()
pause()
```

Argument-order is exactly the same as the existing PWMOutputDevice.blink method.

**Comment by bennuttall** [comment]
Looks good! Could it cope without `on_time` and `off_time` though? Mind you, I can imagine cases you might want it to stay on or stay off between pulses. Yeah, that makes sense.

@waveform80 anything you'd change about this?

**Comment by waveform80** [comment]
My only concern about this is API bloat (it adds a method to a base class, and there's already a method which accomplishes its goals, albeit without default parameters). I'll defer to @bennuttall's judgement on where to draw the line on such things though.

It's also worth noting we already limit which methods appear in the concrete API docs (see the method lists in https://raw.githubusercontent.com/RPi-Distro/python-gpiozero/master/docs/api_output.rst) and hence this method wouldn't automatically appear unless added to the PWMLED list (it will automatically appear in the generic classes docs though as they don't limit which methods appear on the assumption that they're "advanced").

**Comment by bennuttall** [comment]
Ok I'll think about it.

**Comment by lurch** [comment]
Hmmm, maybe it would be worth adding `pulse()` _just_ to the PWMLED class then, rather than the base PWMOutputDevice?
My initial thinking was that `pulse()` was kind-of-like an analogue-equivalent of the digital `blink()` method.

**Comment by waveform80** [comment]
To be honest, that could already be written with PWMLED's blink using `red.blink(0, 0, 1, 1)` out something similar - no need for that while loop :-)

**Comment by lurch** [comment]
Hmmm, `red.pulse()` or `red.blink(0, 0, 1, 1)`... I certainly know which I'd find easier! ;-)

**Comment by bennuttall** [comment]
I think if we were to add a `pulse` method, it should set `on_time` and `off_time` to 0 and only allow configuration of `fade_in` and `fade_out`, otherwise it's exactly the same as `blink`, just with default params, the first two of which you'd have to provide anyway, e.g:

```python
led.pulse(0, 0, 2, 2)
```

or you'd *have* to use named parameters:

```python
led.pulse(fade_in=2, fade_out=2)
```

Whereas with `in_time` and `out_time` not configurable, it would just be:

```python
led.pulse(2, 2)
```

If you need to pulse but leave on or off for any amount of time, just use `blink`.

I was unsure, but I'm warming to the idea now.

**Comment by lurch** [comment]
Fair enough. I guess the other option would be to re-order the arguments of `pulse` to `pulse(fade_in_time, fade_out_time,  on_time, off_time, n, background)` but that's probably just too confusing, so I'm happy to remove the `on_time` and `off_time` parameters, and delegate any more advanced usage to the `blink` method.

What's the consensus about leaving the method in the base `PWMOutputDevice` class, or moving it to just the `PWMLED` class?

**Comment by bennuttall** [comment]
Yeah definitely confusing.

I'm up for merging with my suggestion thrown in. @waveform80, ok?

May as well leave on `PWMOutputDevice`.

**Comment by waveform80** [comment]
All sounds good to me (i.e. leave it on `PWMOutputDevice`, remove `on_time`, `off_time`)

**Comment by bennuttall** [comment]
Looks like TrafficLights doesn't have pulse. I'll look into it.

**Comment by bennuttall** [comment]
Just for fun*, try this with a buzzer:

```python
>>> buzzer = PWMOutputDevice()
>>> buzzer.pulse()
```

* for values of fun = my ears hurt

**Comment by lurch** [comment]
> Looks like TrafficLights doesn't have pulse. I'll look into it.

Yeah, you'll need to add `pulse` to `LEDBoard` too. I was going to add that to the PR at the same time as removing `on_time` and `off_time`, but you beat me to it ;-)

**Comment by bennuttall** [comment]
I like `pulse`. Makes `blink` look boring.

**Pull request merged**
