### PR TITLE
Add tests for LEDBoard.active_high and LEDBarGraph.active_high

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by lurch** [comment]
PR has been updated to also test LEDBoard.value too.
However in doing so I noticed a (possible) slight inconsistency, similar to #212. If we create an LEDBoard with `pwm=True` then only values of 0..1 are accepted, but if we create an LEDBoard with `pwm=False` (which is the default) then *any* values are allowed, as they automatically get coerced to bools. I.e.
```python
>>> from gpiozero.pins.mock import MockPin, MockPWMPin
>>> from gpiozero import LEDBoard
>>> pin1 = MockPin(2)
>>> pin2 = MockPin(3)
>>> pin3 = MockPin(4)
>>> pin4 = MockPWMPin(5)
>>> pin5 = MockPWMPin(6)
>>> pin6 = MockPWMPin(7)
>>> dboard = LEDBoard(pin1, pin2, pin3)
>>> pboard = LEDBoard(pin4, pin5, pin6, pwm=True)
>>> dboard.value = (0, -1, 2)
>>> dboard.value
LEDBoardValue(_0=False, _1=True, _2=True)
>>> pboard.value = (0, -1, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/devices.py", line 299, in __setattr__
    return super(CompositeDevice, self).__setattr__(name, value)
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/devices.py", line 146, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/boards.py", line 81, in value
    device.value = v
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/devices.py", line 146, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/output_devices.py", line 350, in value
    self._write(value)
  File "/home/andrew/tmp_working/python-gpiozero/gpiozero/output_devices.py", line 332, in _write
    raise OutputDeviceBadValue("PWM value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: PWM value must be between 0 and 1
```

**Comment by lurch** [comment]
Alternatively, if we decide that "they automatically get coerced to bools" **is** the expected behaviour, then maybe I ought to modify the changes I made in #303 to also coerce-any-values-to-bools when `pwm=False` is being used; rather than explicitly only allowing 0 or 1 as it does now?  \*shrug\*

**Comment by waveform80** [comment]
Hmmm ... good question. I'm rather tempted to keep the coerced to bools behaviour simply because I tend to think of "pure" digital devices (i.e. non-PWM) as having a bool value (rather than numeric) in which case anything "[truthy](https://docs.python.org/3/library/stdtypes.html#truth-value-testing)" is acceptable as an input. However, PWM and analog devices necessarily have a numeric value; while we may default to float on output we should still accept any numeric input (Fraction, int, etc.) provided it's in range.

Any counter arguments?

**Comment by lurch** [comment]
> Any counter arguments?

Nope, it's a perfectly valid argument.
And I guess modifying the "pure" digital device unit-tests (including `Motor`s constructed with `pwm=False`) to read and write True and False (instead of 0 and 1) would help make this more obvious?

**Comment by waveform80** [comment]
Yeah - I must admit the tests using 0/1 for the digital devices were pure laziness on my part (trying to plough through stuff as fast as possible!).

Do you want me to hold off on merging this for the moment?

**Comment by lurch** [comment]
> Do you want me to hold off on merging this for the moment?

Nah, this PR can be merged as-is. I'll just need to create another PR (following on from the now-merged #303) in which I 'undo' the modifications where I check that non-PWM values are only `0` or `1`.
Changing the 'digital' unit tests to True/False instead of 1/0 should be an entirely different PR.

One possible 'wrinkle' I've just thought of (while cleaning my teeth!), is what to return for devices that can be both 'digital' and 'PWM'...
If we have e.g. a UnidirectionalMotor (as suggested in #315) composed of a single PWMOutputDevice (i.e. constructed with the default `pwm=True`), then the result of the `value` property-getter will always be a float between 0 and 1. And the input to the `value` property-setter will also always be a float between 0 and 1.
Whereas if we have a UnidirectionalMotor constructed with `pwm=False` (i.e. composed of a single DigitalOutputDevice), then the input to the `value` property-setter is effectively a boolean value. However to maintain compatibility with the pwm-able UnidirectionalMotor, we should probably still return "a float between 0 and 1" from the `value` property-getter (i.e. `0.0` for 'off' and `1.0` for 'on'). Does it make sense for the value-getter to return a float, but the value-setter to (implicitly) operate on bools?

Maybe I'm just worrying about nothing, given the auto-conversion that Python does between bool/int/float ? Still, good to get the expected / defined behaviour fully hammered out :-)


(And I guess `Motor`s constructed with `pwm=False` will still need to operate with the float values (for both setting and getting) of `-1.0`, `0`, `1.0`, since a bool can't represent the three different states. So I guess setting a Motor with `pwm=False` to `-1.0` will drive it backwards, whereas setting a UnidirectionalMotor with `pwm=False` to `-1.0` will drive it forwards (remember that Motor is a subclass of UnidirectionalMotor). Hmmm, maybe I need to think about this more tomorrow when I'm not so tired!)

**Comment by lurch** [comment]
...although even for `Motor`s with `pwm=False`, the optional argument to `forward()` and `backward()` _could_ still be coerced to bool, making `motor.forward(-2)` === `motor.forward(True)` === `motor.forward()`.

Still not sure what the most reasonable behaviour is, so happy to go along with whatever @waveform80 recommends. But whatever behaviour we *do* settle on, I think RGBLED, Motor, UnidirectionalMotor, LEDBoard, etc. should probably all work in the same way (in terms of value setters and getters). Currently [RGBLED](https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/output_devices.py#L605) with `pwm=False` works differently to [LEDBoard](https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/boards.py#L78) with `pwm=False`; the former only allows a tuple of `0` / `1` (or `False` / `True`) values but the latter accepts a tuple of any values, coercing each of them to bool. (Whereas when constructed with `pwm=True`, they both only accept a tuple of (values that can be coerced to) floats between 0 and 1 inclusive).

Apologies if I'm unnecessarily overcomplicating things :-/

**Comment by waveform80** [comment]
> Apologies if I'm unnecessarily overcomplicating things :-/

No, they're good points - I'll need to think a bit about this but I'm currently hip-deep in a gdb backtrace in picamera that's segfaulted somewhere in libffi (god help me), so I'll have to leave it for the weekend. Anyway, I'll merge this now :)

**Pull request merged**
