### PR TITLE
Support extra models - CM3, Sony Japan Pi 3B & Pi Zero W

### LINKED ISSUE #527: Failed to parse pi revision
I got an error saying:
> gpiozero.exc.PinUnknownPi: unable to parse new-style revision "a32082"

My raspi is made-in-Japan Raspberry Pi 3 Model B released in November 2016.
Its revision is:
```
$ cat /proc/cpuinfo | tail -3
Hardware	: BCM2709
Revision	: a32082
Serial		: 00000000a31110c1
```

I should have bought UK model...

### PR DESCRIPTION
**Pull request by lurch**
Fixes #527

### CODE REVIEW

**Comment by lurch** [comment]
This will probably need to be rebased after #530 gets merged.

**Comment by charlton91** [comment]
Do we know when this will be merged into the master branch?

**Comment by lurch** [comment]
I've now updated this PR to also support (and provide details for) the new [Pi Zero W](https://www.raspberrypi.org/blog/raspberry-pi-zero-w-joins-family/)
:-)

**Comment by bennuttall** [comment]
Thanks @lurch I made this change last night but didn't get chance to test it.

I think we should reset back to the last release, merge this PR and do a 1.3.2 release. We can't have Made In Japan and Pi Zero W users not able to use gpiozero.

How happy are you with the state of the PR @lurch @waveform80?

**Comment by lurch** [comment]
I could rebase this PR on top of https://github.com/RPi-Distro/python-gpiozero/tree/v1.3.1.post1 if you like? (or feel free to do that yourself if there's no merge conflicts)

> We can't have Made In Japan and Pi Zero W users not able to use gpiozero.

Agreed.

> How happy are you with the state of the PR @lurch @waveform80?

Well, I'm happy with it, otherwise I wouldn't have submitted it ;-)  I obviously can't speak for Dave though.

BTW the latest commits in this PR were created and submitted entirely from a Pi Zero W that I'd connected to via SSH over WiFi :smiley_cat:

**Comment by waveform80** [comment]
Just merged the 1.3.2-updates branch into master and hopefully I've managed to include everything from here with it; I've tested it with manually specifying revisions for CM3, Zero W, and various old & new boards - all seems happy for now so I'll close this but someone should probably check I'm not leaving anything out!

**Comment by lurch** [comment]
Yeah, things got a bit crazy for a couple of days (right before the RPi birthday party IIRC) where Ben needed to push out a new version of GpioZero which supported the Pi Zero W, but he couldn't create a new release off `master` because that had moved too far ahead, so I had to backport various fixes on top of the `1.3.1` release tag. I meant to come back to it and update this PR to include all the same changes, but I guess I must have forgotten to.

I'll try to have a look at things tomorrow (I'm out this evening) to check that everything looks okay.

**Comment by waveform80** [comment]
Just got back to it (too many things going on today!) and I've messed up a small bit with the release dates. Just fixing that up now and I'll push it in a mo while I'm merging your lenient_revision_parser branch (not sure if the mix up is from that branch or what I've just merged, but who cares as long as it's alright in the end - I'm being a bit rough'n'ready with the merging right now so I can try and get back to a reasonable state for the heavier remote-spi branch later this week)

**Pull request closed without merging**
