### PR TITLE
Add release date for new BCM2837-based Pi 2B

### PR DESCRIPTION
**Pull request by bennuttall**
I think this is all that's needed to make `pi_info()` accurate

### CODE REVIEW

**Comment by waveform80** [comment]
Er, shouldn't that be against 2B instead of B+?

**Comment by bennuttall** [comment]
I have no idea how I managed that.

**Comment by lurch** [comment]
Are you sure this is correct? The _current_ 2B (2015Q1) has a revision of 0xa01041 which decodes to a pcb_revision of 1.1

**Comment by waveform80** [comment]
Yup, so the current one (rev 1.1) will have a release date of 2015Q1, the new (rev 1.2) will have 2016Q3

**Comment by lurch** [comment]
Doh! I misread the 'if' logic as the other way around. Ignore me... ;-)

**Comment by lurch** [comment]
Although... given that http://elinux.org/RPi_HardwareHistory mentions an a01040, should the 'if' be expanded to `if pcb_revision == '1.0' or pcb_revision == '1.1'` ?

**Comment by waveform80** [comment]
Yeah, not a bad idea

**Comment by lurch** [comment]
That's cool - I didn't know github let you edit other people's PRs. Hope you don't mind Ben!
IMHO we should get verification of the revision code on an actual 2837-based Pi 2B before this gets merged.

**Comment by waveform80** [comment]
> That's cool - I didn't know github let you edit other people's PRs.

It's a recent thing. There's a new check-box when creating a PR labelled something like "allow maintainers to edit PR" which permits it (it's checked by default).

**Comment by bennuttall** [comment]
It's `a22042`

**Comment by lurch** [comment]
> It's a22042

Cheers. I've just updated http://elinux.org/RPi_HardwareHistory

**Pull request merged**
