### PR TITLE
Add socket method for Energenie

### PR DESCRIPTION
**Pull request by SteveAmor**
Replaces #486

### CODE REVIEW

**Comment by bennuttall** [comment]
Thanks @SteveAmor :+1: 

Note: docs currently show no useful properties/methods for Energenie, I think things like on/off/socket need to be specified.

**Comment by SteveAmor** [comment]
@bennuttall building the docs is very broken.  First off, it complains about not having Sphinx installed.  I installed Sphinx with pip and then when you run ```make doc``` pretty well everything errors and the build fails.  So I can't test that I've updated the docstrings correctly :-(

**Comment by bennuttall** [comment]
I assume it's `apt install sphinx` rather than `pip`. If that's missing in the docs, we'll add it.

I can't test easily as I know I have a working setup on my machine, but I guess I could always try on a Pi.

**Comment by SteveAmor** [comment]
sudo apt install sphinx
E: Unable to locate package sphinx
:-(  Hence trying pip :-(

**Pull request merged**
