### PR TITLE
Add a new alternating_values SourceTool

### PR DESCRIPTION
**Pull request by lurch**
Another way of implementing this would be:
```python
def alternating_values(initial_value=False):
    return cycle([initial_value == True, initial_value == False])
```
but I think the version in this PR is a bit more readable ;-)

### CODE REVIEW

**Comment by bennuttall** [comment]
That's cool. I don't know which I consider neater. Both nice :)

**Comment by bennuttall** [comment]
I also suggested to Dave adding a booleanised `random_values` function i.e. randomly on or off for a non-pwm device. But that's easy enough to achieve by processing `random_values`.

**Comment by lurch** [comment]
That's exactly what http://gpiozero.readthedocs.io/en/latest/api_tools.html#gpiozero.tools.booleanized is for ;-)

**Comment by bennuttall** [comment]
That's what I meant!

**Comment by lurch** [comment]
...which means a very inefficient **third** way of implementing this PR would be:
```python
def alternating_values(initial_value=False):
    it = booleanized(cos_values(2), 0, 1)
    if not initial_value:
        it = negated(it)
    return it
```

;-)

**Comment by waveform80** [comment]
Oh, that's nice. As I think I mentioned at PyConUK - source/values is by far my favourite bit of the library!

**Comment by lurch** [comment]
I'm thinking of adding `ramping_values` next, which will be like a 'linear' version of `cos_values` (i.e. a triangle wave).

**Comment by waveform80** [comment]
Ahh - I was wondering when someone (or myself) would get around to a triangle wave! I wonder if there should be aliases like square_values and triangle_values for these things?

**Comment by lurch** [comment]
> I wonder if there should be aliases like square_values and triangle_values for these things?

I'm not sure... I guess `triangle_values` _could_ be aliased to `ramping_values`, but I think if we wanted a `square_values` function then it'd need a `period` parameter (which `ramping_values` will have).

Do you think I should make `ramping_values` output 0 -> 1 (like `alternating_values` effectively does), or -1 -> +1 (like `cos_values` does) ?  My inclination is the former. (Obviously either variant can be `scaled` to the other one afterwards)

**Comment by waveform80** [comment]
Ah, good point about the `period` parameter. And yes, my gut says 0->1 as well. Scaling's easy enough to apply.

**Pull request merged**
