### PR TITLE
Catch AttributeError inside GPIODevice._read

### LINKED ISSUE #202: repr is broken for closed devices
Example interactive code:
```python
>>> from gpiozero import LED
>>> led = LED(21)
>>> led
<gpiozero.LED object on pin GPIO21, active_high=True, is_active=False>
>>> led.close()
>>> led.closed
True
>>> led
Traceback (most recent call last):
  File "gpiozero/output_devices.py", line 88, in __repr__
    self.__class__.__name__, self.pin, self.active_high, self.is_active)
  File "gpiozero/devices.py", line 323, in value
    return self._read()
  File "gpiozero/devices.py", line 245, in _read
    return self.pin.state == self._active_state
AttributeError: 'NoneType' object has no attribute 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpiozero/output_devices.py", line 90, in __repr__
    return super(OutputDevice, self).__repr__()
  File "gpiozero/devices.py", line 330, in __repr__
    self.__class__.__name__, self.pin, self.is_active)
  File "gpiozero/devices.py", line 323, in value
    return self._read()
  File "gpiozero/devices.py", line 245, in _read
    return self.pin.state == self._active_state
AttributeError: 'NoneType' object has no attribute 'state'
```

### PR DESCRIPTION
**Pull request by lurch**
Fixes #202

### CODE REVIEW

**Comment by lurch** [comment]
At least, I *believe* this is the correct fix. Obviously @waveform80 will need to confirm.

**Comment by lurch** [comment]
PR updated with appropriate unit-tests :-)

**Comment by waveform80** [comment]
And tests too! I love PRs like this :)

**Comment by waveform80** [comment]
(and yes, it's the correct fix - I think the pins implementation broke that by mutating the TypeError, which RPi.GPIO raises, to an AttributeError)

**Comment by lurch** [comment]
> And tests too! I love PRs like this :)

:-D

**Pull request merged**
