### PR TITLE
Fix SmoothedInputDevice to use the mean of the values, matching the docs

### LINKED ISSUE #615: SmoothedInputDevice (wrongly?) uses the Median (instead of the Average) on the queue to return the value
While in the documentation it says that the *mean* or *average* of the values in the internal queue will be compared to `threshold` to determine whether device `is_active`, `.value` in fact returns the **median** of the queue. I fixed it for myself in `mixins.py`, by importing the `mean` and then passing it as the default `average` keyword parameter to the `__init__()`-function of `GPIOQueue()`.

I wonder whether taking the median serves a purpose i'm unaware of (apart from contradicting the documentation, hehe), but given digital inputs, the median can only return 0 or 1 (or very rarely 0.5), strongly reducing the functionality of the `threshold`.

I suggest changing that behavior to using the **arithmetic mean** instead of the median?

### PR DESCRIPTION
**Pull request by lurch**
Fixes #615 

I'm afraid I couldn't think of any way of unit-testing this.

### CODE REVIEW

**Comment by waveform80** [comment]
Oh hell - I actually said mean in the docs. Hmmm. I'm sorely tempted to change the docs to say median (or just more vaguely "average") rather than switch to mean (median's awfully nice for discarding silly outliers which is exactly what we want for jittery sensors - fully half the queue's values have to be "wrong" before the median is affected, unlike the mean).

**Comment by bennuttall** [comment]
That makes sense, do you want to just use median?

**Comment by holzfigure** [comment]
i'm using the SmoothedInputDevice to read back values from a PWMOutputDevice, where i really need the "mean", otherwise i only get either 0 or 1. But maybe that's a silly way of me to try to achieve reading the PWM easily.. ?

**Comment by waveform80** [comment]
Yes, to be honest I'd much rather stick to median, and expose the choice to the user (and correct the docs to say something vague like "average") rather than switch to mean. For things like DistanceSensor, median is *much* better as it means the occasional "max distance" reading (which can occur when an echo edge is missed) doesn't "leap" the reading.

Exposing it to the user shouldn't be too hard - just means exposing some more params of GPIOQueue in SmoothedInputDevice and its descendants. I'll see if I can squeeze that in tonight.

**Comment by waveform80** [comment]
Actually not even the descendents - just SmoothedInputDevice would do for @holzfigure's use case. Right, I'll bash this together now.

**Comment by holzfigure** [comment]
Thanks so much! This is perfect for my use case and allows for so much more fun! ,)

**Pull request closed without merging**
