### PR TITLE
Fix #114

### LINKED ISSUE #114: HC-SR04 Ultrasonic Sensor
Another one from camjam kit 3, see the [worksheet](https://drive.google.com/file/d/0B61nxMOqZJ0YX3drV3FIZzEzNG8/view)

Example code:

```python
pinTrigger = 17
pinEcho = 18

GPIO.setup(pinTrigger, GPIO.OUT)
GPIO.setup(pinEcho, GPIO.IN)

while True:
    GPIO.output(pinTrigger, False)
    time.sleep(0.5)

    # Send 10us pulse to trigger
    GPIO.output(pinTrigger, True)
    time.sleep(0.00001)
    GPIO.output(pinTrigger, False)

    StartTime = time()
    # The start time is reset until the Echo pin is taken high (==1)
    while GPIO.input(pinEcho) == 0:
        StartTime = time()
    # Stop when the Echo pin is no longer high - the end time
    while GPIO.input(pinEcho) == 1:
        StopTime = time()
        # If the sensor is too close to an object, the Pi cannot
        # see the echo quickly enough, so it has to detect that
        # problem and say what has happened
        if StopTime-StartTime >= 0.04:
            print("Hold on there! You're too close for me to see.")
            StopTime = StartTime
            break
    # Calculate pulse length
    ElapsedTime = StopTime - StartTime
    # Distance pulse travelled in that time is
    # time multiplied by the speed of sound (cm/s)
    Distance = ElapsedTime * 34326
    # That was the distance there and back so halve the value
    Distance = Distance / 2
    print("Distance : %.1f" % Distance)
    time.sleep(0.5)
```

### PR DESCRIPTION
**Pull request by waveform80**
Implements support for the HC-SR04 ultrasonic sensor as an input device
class named DistanceSensor

### CODE REVIEW

**Comment by bennuttall** [comment]
Is this complete? I'll give it a try

**Comment by waveform80** [comment]
See comments on #114; TL;DR: yes it's complete but I'd welcome any suggestions on better names for the events.

**Comment by bennuttall** [comment]
Ok cool

**Comment by bennuttall** [comment]
Where the hell is my ultrasonic sensor?

**Comment by lurch** [comment]
> Where the hell is my ultrasonic sensor?

Is it `near`, or is it `far`? ;-D

**Comment by bennuttall** [comment]
If only I had one, maybe I'd know!

**Pull request merged**
