### PR TITLE
Allow AngularServo to have an initial_angle of None.

### LINKED ISSUE #476: Cannot create AngularServo with initial_angle=None
Attempting to run the following code snippet results in a TypeError exception.

`import gpiozero`
`s=gpiozero.AngularServo(21,initial_angle=None)`

Traceback:
`Traceback (most recent call last):`
`File "<pyshell#33>", line 1, in <module>`
`s=gpiozero.AngularServo(21,initial_angle=None)`
`File "/usr/lib/python2.7/dist-packages/gpiozero/devices.py", line 135, in __call__`
`self = super(GPIOMeta, cls).__call__(*args, **kwargs)`
`File "/usr/lib/python2.7/dist-packages/gpiozero/output_devices.py", line 1157, in __init__`
`initial_value = 2 * ((initial_angle - min_angle) / self._angular_range) - 1`
`TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'`

While unclear, the documentation suggests that this should be possible in order to start the servo uncontrolled. Exception does not occur if "initial_angle" is omitted or set to a suitable numeric value. "Pin" value appears to have no effect on this either.

### PR DESCRIPTION
**Pull request by lurch**
Fixes #476 by doing a bit of refactoring.

### CODE REVIEW

**Comment by bennuttall** [comment]
Looks good to me

**Comment by bennuttall** [comment]
Is this a duplicate of #491?

**Comment by lurch** [comment]
LOL, WTF?! :upside_down_face:  Got no idea why I made two such similar PRs within the space of less than a month!!! :rofl: 

If I get a chance over the weekend I'll have a look in more detail to see if they really are duplicates (and if they are, which one should be kept open and which one should be closed)

**Comment by waveform80** [comment]
Any preference on these? #491 has no conflicts as it's a bit more minimal. The tests need tweaking for pin construction in either, but I could do that in a few minutes if one if preferred? Personally I'd go with #491 simply on the principle of least change, though the tests are a bit more comprehensive in this one.

**Pull request closed without merging**
