### PR TITLE
remove usage of CompositeDevice.all since it's marked as deprecated

### PR DESCRIPTION
**Pull request by lurch**
https://github.com/RPi-Distro/python-gpiozero/blob/master/gpiozero/devices.py#L321

### CODE REVIEW

**Comment by bennuttall** [comment]
Should we not leave it for a while to save BC, and remove later (say, v2.0?) @waveform80?

**Comment by lurch** [comment]
Yes, I agree. I didn't remove the function itself, I only updated other parts of gpiozero to no longer call it ;-)

**Comment by bennuttall** [comment]
Oh I see. Yeah that's cool.

**Comment by waveform80** [comment]
Yup, that's perfect :)

**Pull request merged**
