### PR TITLE
Bump coverage a tiny amount, and fix a genuine bug

### PR DESCRIPTION
**Pull request by lurch**
(the bug is that `spi_devices.py` wasn't importing `InputDeviceError`)

### CODE REVIEW

**Comment by lurch** [comment]
Hmmm, Travis is telling me that the tests all pass on Py2.x and Py3.x but fail on pypy and pypy3 with:
```
GPIOPinInUse: pin 4 is already in use by <gpiozero.InputDevice object on pin GPIO4, pull_up=None, is_active=False>
```

Any ideas @waveform80 ?

**Comment by tuftii** [comment]
Is this the same GPIO pin in use thing we saw in #680?

**Comment by lurch** [comment]
@tuftii It's similar, but I don't think it's the same thing. IIRC the bug you found affected all versions of python, where the bug here is only affecting pypy.

**Comment by waveform80** [comment]
@lurch yup - the issue is the pypy GC is too slow at destroying the first InputDevice on GPIO4. It's fine in other tests where "with" is used as the context manager will explicitly close the device (no waiting for the GC). But the first test in `test_input_invalid_external_pull_configuration` is constructing a bare InputDevice outside a "with" section (which is entirely correct BTW, but in this case it'll cause this issue with pypy). I've just pushed a simple fix which is to separate it into two tests; the mock_factory cleanup will explicitly close all attached devices which should deal with the issue.

**Pull request merged**
