### PR TITLE
MockPin improvements

### LINKED ISSUE #206: MockPin 'breaks' the Pin interface?
According to the "Abstract Pin" [documentation](http://gpiozero.readthedocs.org/en/latest/api_pins.html#abstract-pin) 

> Warning: Descendents must ensure that pin instances representing the same physical hardware are identical, right down to object identity.

and `MockPin` is a descendant of `Pin`. I realise the MockPin doesn't refer to _actual_ hardware, but it might be nice (for the sake of the unit-tests) if
```python
from gpiozero.pins.mock import MockPin
pin1 = MockPin(3)
pin2 = MockPin(3)
print(pin1 == pin2)
```
printed `True`, as it does for all the other `Pin` subclasses (with the current MockPin implementation it prints `False`).
In turn, this would allow us to have unit-tests for checking that e.g.
```python
from gpiozero.pins.mock import MockPin
from gpiozero import LED
led1 = LED(MockPin(3))
pin2 = LED(MockPin(3))
```
fails with `GPIOPinInUse` as all the other `Pin` subclasses do.

I tried having a go myself at modifying the MockPin class to behave like the other Pin implementations (by changing `__init__` to `__new__` , adding a `_PINS` dict, etc.) but that just caused a whole load of problems with `MockPWMPin` then not working.

Feel free to close this issue, if it's irrelevant and I've misunderstood things!

### PR DESCRIPTION
**Pull request by lurch**
Change MockPin (and MockPWMPin) to make them behave more like 'real' pins - fixes #206
Add new MockPin tests, and rework some of the existing ones
Incorporate #216

### CODE REVIEW

**Comment by lurch** [comment]
"The Travis CI build failed" - oh arse!  I'd only been testing with Python2.7 and Python3.2  :-(

**Comment by lurch** [comment]
So, if I change https://github.com/RPi-Distro/python-gpiozero/pull/217/files#diff-cb8d4fe36ad4392bcf34acd42c33a0e9R172 to `super(MockPWMPin, self).__init__()` then I guess it'd stop Python3.3+ complaining; and surprisingly the tests all still pass in my Python2.7 and Python3.2 venvs with that change. Out of curiosity, how come 2.7 and 3.2 worked okay?

Is the error from Python3.3+ because neither `MockPin` or `Pin` have an `__init__` method of their own, and so `super(MockPWMPin, self).__init__` ends up calling `object.__init__` as the parent-class of `Pin`?

**Comment by lurch** [comment]
I found the answer here: http://stackoverflow.com/questions/14300153/why-does-this-datetime-subclass-fail-on-python-3/  (my guess about `object.__init__` was correct; and this was behaviour only enforced in Py3.3 - the old behaviour being allowed in Py2.7 and Py3.2 was a bug).

PR updated, and now the Travis builds all pass! :-)

**Comment by waveform80** [comment]
Hehe - and that's why I love having a test suite; I can't describe how nerve-wracking it was doing release 1.0 and 1.1 of gpiozero without any test suite in place! Anyway - this now looks excellent - the factoring out of `_change_state` is particularly nice with the return value determining whether anything *actually* changed state. Many thanks!

**Comment by lurch** [comment]
> the factoring out of _change_state is particularly nice

Yeah, I thought so too :)  Thanks for merging!

**Pull request merged**
