### PR TITLE
Fix #320

### LINKED ISSUE #320: Broken link in documentation
I've just noticed that the "Contribute" link on http://gpiozero.readthedocs.io/en/latest/index.html#development gives a 404 error.

### PR DESCRIPTION
**Pull request by waveform80**
Yup, dirty horrid hack but the result is okay.

### CODE REVIEW

**Comment by lurch** [comment]
Hmm, I've just noticed that the `recipes` link on http://gpiozero.readthedocs.io/en/v1.2.0/#development links to `http://gpiozero.readthedocs.org/en/latest/recipes.html`, and I guess this new `contribute` link will behave the same (once it makes it into 'stable'). Note the mismatch between `v1.2.0` and `latest`.

Is there any way the absolute URL could be converted back into a relative URL during the sphinx process, i.e. so that the `recipes` link mentioned above would then be just `recipes.html` ?  (which I guess would also make it work better for the offline docs)

**Comment by waveform80** [comment]
I wish there were, but no - GitHub's reST renderer doesn't understand substitutions so there's no way I can make the link any more nuanced and have it work under both GitHub and RTD. On RTD alone I could do it (simple `:ref:` link).

**Comment by lurch** [comment]
Would having separate index / README pages for RTD and Github be too much of a maintenance burden then? (or is the index of RTD automatically the Github README / vice-versa?)

**Comment by waveform80** [comment]
The RTD index is only the same as README because I `.. include` it - in other words, it's my DRY sense in overdrive (I always try and remove redundancy so there's as few places to update as possible - otherwise sod's law I always forget one). Still, you're right - it's not such a big deal to have a separate index and README.

**Comment by bennuttall** [comment]
Unfortunately GitHub doesn't pick up `CONTRIBUTING.RST`.

See the difference between [RPi-Distro/python-gpiozero](https://github.com/RPi-Distro/python-gpiozero/issues/new) and [RPi-Distro/python-sense-hat](https://github.com/RPi-Distro/python-sense-hat/issues/new).

From https://github.com/blog/1184-contributing-guidelines:

> As a maintainer, all you have to do is add a CONTRIBUTING file (or CONTRIBUTING.md if you're using Markdown) to the root of your repository.

**Comment by waveform80** [comment]
Eurgh ... sometimes GitHub really annoys me. Okay, I'll revert it and figure something out (even if it is duplicating something)

**Comment by lurch** [comment]
@waveform80 Did this actually get reverted? Was it supposed to have been? The root of this repo still has no CONTRIBUTING or CONTRIBUTING.md file.

**Comment by waveform80** [comment]
Erm, good question - there's e9ff6fce3cb33fff4c3792a1ffc5eab6bbc210f0 which reverts the Fix #295 patch but I never got around to introducing a CONTRIBUTING file.

**Pull request merged**
