### PR TITLE
Update output_devices.py

### PR DESCRIPTION
**Pull request by goloplo**
To be able to use all the Pins when using a Motor. Maybe future definition for modifying the speed (PWM) should be added as separate command.

### CODE REVIEW

**Comment by lurch** [comment]
I don't think this fix is correct as-is (it would break existing code that relies on the Motor class supporting variable speeds), but it does raise an interesting point - there should probably be some way to use the Motor class with digital-only pins (which would only give you forwards / off / backwards controls rather than variable speed controls), in order to be able to use Motor objects with pins (e.g. on GPIO-expanders) that aren't capable of PWM (and are too slow for software PWM).
Whether that should be a new 'DigitalMotor' class, or some variant of the existing Motor class (that then raises Exceptions if you try to set a `value` other than 1 / 0 / -1) will need to be thought about. This also overlaps nicely with the discussion in #276 and https://github.com/RPi-Distro/python-gpiozero/pull/277#issuecomment-211608633

**Comment by waveform80** [comment]
Why on earth did I write 0.01µF there... oh well, decimals on the brain :)

**Comment by waveform80** [comment]
What on earth am I doing ... wrong comment on the wrong PR ... damnit, get a grip man!

**Comment by lurch** [comment]
This has now been fixed with #303

**Pull request merged**
