### PR TITLE
Fix #295

### LINKED ISSUE #295: Privacy breach: local documentation shouldn't include Travis build status
As discussed in #284.

The documentation available at http://gpiozero.readthedocs.org/en/latest/ includes the Travis build status. This is useful.

The build status shouldn't be included in the documentation intended to be read offline, specifically in the Debian package of documentation.

### PR DESCRIPTION
**Pull request by waveform80**
At least, I *think* this should fix this. It does locally, but we'll
have to see what happens when I push it to RTD!

### CODE REVIEW

**Comment by lurch** [comment]
Could something similar be used to re-do #403 in a better way?

**Comment by lurch** [comment]
P.S. When you use "Fix #nnn" as your PR title, it's a shame that github doesn't auto-linkify it to the corresponding issue :-/

**Comment by lurch** [comment]
OTOH this fix means that the build-status buttons have now disappeared from https://github.com/RPi-Distro/python-gpiozero :-(  So maybe we really do need separate readme / index files for github and the documentation? (or maybe you could have a git-commit-hook so that updating one automatically updates the other)

**Comment by waveform80** [comment]
> Could something similar be used to re-do #403 in a better way?

Possibly - will have to check on that.

> P.S. When you use "Fix #nnn" as your PR title, it's a shame that github doesn't auto-linkify it to the corresponding issue :-/

No kidding - really annoying when Trac used to do exactly that (I still miss some things about Trac...)

> OTOH this fix means that the build-status buttons have now disappeared from https://github.com/RPi-Distro/python-gpiozero :-( So maybe we really do need separate readme / index files for github and the documentation? (or maybe you could have a git-commit-hook so that editing one automatically generates the other)

Yeah - saw that last night and said to myself "it's midnight ... declare victory for now". I'll try and get around to fixing it at some point, but it's kinda low down the list. Unfortunately GitHub's reST implementation doesn't know about the ifconfig extension (for that matter it doesn't properly degrade with unknown tags which is kinda crap). Anyway - any suggestions welcome, but for now I'm saying "good enough".

**Pull request merged**
