### PR TITLE
add RPi.GPIO to dependencies

### LINKED ISSUE #387: [performance] Button - huge CPU hog
Whenever I instantiate the Button class, I get ca. 35% CPU load per instance:

1. run "sudo python3" in one console and open "top" or "htop" in another one for monitoring
2. find the python3 process in the top list
3. enter in python interactive mode:

`import gpiozero`
`button1 = gpiozero.Button(4)`

EFFECT: +30...35% CPU load by python3 after instantiation of Button
SHOULD BE: CPU load doesn't rise drastically

Now try creating some more Button instances for different GPIO pins:

`button2 = gpiozero.Button(24)`

EFFECT: the CPU load rises proportionally, causing the Raspberry to run out of resources if too many instances are created

Try to get rid of the instances:

`button1 = None`
`button2 = None`

EFFECT: CPU load doesn't drop
SHOULD BE: instances are deleted and the load drops

Exit the interpreter:

`exit()`

EFFECT: the CPU load finally comes back to normal.

Tested on the old RPi B rev 2 and B+, Raspbian stretch, Python 3.5.2

### PR DESCRIPTION
**Pull request by elegantandrogyne**
fix #387

### CODE REVIEW

**Comment by bennuttall** [comment]
gpiozero doesn't depend on RPi.GPIO. If it's present, we use it. If it's not, there are fallback alternatives. For example, some people will want to use RPIO for its better PWM support.

And you can even install gpiozero on a PC, and use pigpio's remote GPIO functionality to create gpiozero objects referring to pins on a Pi over a network - so the GPIO library itself is not required.

**Comment by lurch** [comment]
@bennuttall So, RPi.GPIO isn't a dependency in `setup.py`, but it *is* a dependency in `debian/control`...?
See also my comments in https://github.com/RPi-Distro/python-gpiozero/issues/359#issuecomment-225455765

**Comment by bennuttall** [comment]
It should be removed from debian/control.

**Comment by bennuttall** [comment]
(and added to recommends)

**Comment by waveform80** [comment]
That's now done (#399)

**Pull request closed without merging**
