### PR TITLE
Tweak the ADC classes to make the docs neater and more accurate

### PR DESCRIPTION
**Pull request by lurch**
If I've done anything the "wrong way" in this PR, I'm happy to make any changes requested before it gets merged.

As with #277 I'll leave it up to @waveform80 to regenerate the images and docs ;)

### CODE REVIEW

**Comment by bennuttall** [comment]
Looks good to me

**Comment by lurch** [comment]
PR has been updated to also add the images.

**Comment by waveform80** [comment]
I note this is marked "in-progress"; I'm about to PR a load of stuff which basically implements a full SPI test suite (along with some SPI fixes). @lurch - any objections if I merge this first (there's some good stuff in here and I can pull it into my spi-tests branch more easily if it's upstream)?

**Comment by lurch** [comment]
I dunno why it was marked as "in-progress". I've got nothing left to add to it, so feel free to merge! :-)

**Comment by waveform80** [comment]
Excellent, thanks!

**Comment by bennuttall** [comment]
FYI the "in-progress" label comes from waffle.io - I was trying it out the other day. Useful tool I haven't used for ages. It lays out your issues in columns like trello. I was trying to organise things, see which issues are easy wins. Check it out at https://waffle.io/RPi-Distro/python-gpiozero

**Comment by waveform80** [comment]
Hmm, can't say I ever got along with Trello (or Waffle). I'm generally happier filtering result sets in GitHub's issues and PRs list (but then I tend to think in terms of databases more than most, I suspect). But if you find it useful, go for it.

**Pull request merged**
