### PR TITLE
Update sourcetools examples

### PR DESCRIPTION
**Pull request by lurch**
Remove blue.source_delay, as it's actually red.source_delay that controls the speed of the fading

### CODE REVIEW

**Comment by bennuttall** [comment]
Is that not intentional?

**Comment by waveform80** [comment]
Hmm, sort of. As it happens both are redundant as the default delay is actually 1/100th of a second, so they're really just there for show. Still, it's wise to specify both as the blue thread's delay could be *longer* than the red thread's at which point one LED would appear to fade "choppily" ... if that's a word.

**Comment by lurch** [comment]
Fair enough. In spirit of DRY, what if we instead changed it to `blue.source_delay = red.source_delay` ?

**Comment by waveform80** [comment]
Sounds good to me!

**Comment by lurch** [comment]
PR updated :)

**Pull request merged**
