### PR TITLE
Corrected value of capacitor used in LightSensor

### PR DESCRIPTION
**Pull request by SteveAmor**
CamJam kit has a 1uF capacitor in it. Plus I physically tested with the 1uF cap in my CamJam #2 kit.

### CODE REVIEW

**Comment by lurch** [comment]
Yep, https://github.com/CamJam-EduKit/EduKit2/raw/master/CamJam%20EduKit%202%20-%20Sensors%20Worksheet%204%20-%20Light.pdf confirms that it's 1µF. Could you also update your PR to use a capital 'F' ?

**Comment by waveform80** [comment]
Why on earth did I write 0.01µF there... oh well, decimals on the brain :)

Got the right PR this time too...

**Comment by lurch** [comment]
> Got the right PR this time too...

:-D

**Comment by SteveAmor** [comment]
@waveform80 this is the PR I was babbling on about in the pub - https://github.com/raspberrypilearning/laser-tripwire/pull/3

**Comment by waveform80** [comment]
@SteveAmor ahh, looks like that one needs rebasing first, unfortunately (and I don't have commit access on those repos so there's not much I can do to help). I located your other PRs on the physical computing guide - DM'd Ben about it and apparently he suspects that resource isn't used anymore (I can't locate the link to it on https://www.raspberrypi.org/resources/ - I assume it's been superseded by the python and scratch-specific guides) which is probably why no-one's noticed them - sorry!

**Comment by bennuttall** [comment]
I've fixed the laser-tripwire one. The physical computing resource has been replaced with a set of GPIO Zero ones.

**Pull request merged**
