### PR TITLE
Add a `pwm` option to the RGBLED and Motor constructors

### PR DESCRIPTION
**Pull request by lurch**
...along with the other necessary changes required, to allow them to optionally be used with non-PWM-capable pins.

IMHO this is the 'proper' way of implementing the change suggested in #301

### CODE REVIEW

**Comment by lurch** [comment]
Please merge #312 before merging this, and then I'll update this PR as appropriate.

**Comment by waveform80** [comment]
#312 merged so this is now showing a conflict

**Comment by lurch** [comment]
PR now rebased and updated.

It may _look_ like this PR is removing `test_output_pwm_pulse_background` and `test_output_pwm_pulse_foreground`, but in this morning's merge-fest they somehow got added twice (I guess I must have had slightly-different implementations of the same test function in two different PRs or something).

**Comment by waveform80** [comment]
No prob - and yes, I think this probably the correct fix to #301 (though I still think #219 is a great idea too - I just don't have time to dig into it thoroughly right now).

**Comment by waveform80** [comment]
Anyway, I'll merge this and we can consider #219 later when I'm back from picamera!

**Comment by lurch** [comment]
Thanks for merging! Now to rebase all my other branches... ;)

**Pull request merged**
