### PR TITLE
Docs config

### PR DESCRIPTION
**Pull request by waveform80**
Few things for the docs:

1. Reduce the levels on the index; as it stands it's enormous and frankly scary for newbies ("I've got *all that* to read?!")
2. Tidy up the PDF output (page numbers for anyone doing hardcopy)
3. Add the beginnings of a FAQ

### CODE REVIEW

**Comment by bennuttall** [comment]
Thanks @waveform80. Looks good to me. I've pushed your branch to this repo and enabled it on RTD. In future can you push your PR branches to this repo so that we can easily enable it in RTD?

Any reason you went for "device sources" instead of "source tools"? I think I preferred "source tools".

We need more remote & advanced recipes. I'll see what I can come up with. And I need to finish the Windows/Mac installation steps.

I will add a screenshot to the pinout tool docs page.

**Comment by bennuttall** [comment]
Ok it's merged so now on master and will be on RTD "latest" in a moment.

**Comment by bennuttall** [comment]
In the remote gpio docs I've referred to the PC as the "host computer". Seeing as pigpio refers to the Pi by its "host" (IP/hostname), should we consider using another name for this?

**Comment by waveform80** [comment]
> Any reason you went for "device sources" instead of "source tools"? I think I preferred "source tools".

It sounded a little ambiguous to me. "Source tools" could mean stuff to do with source code, while "device sources" ... well it's still a little ambiguous (could mean "source code for devices") but it's slightly better :)

> We need more remote & advanced recipes. I'll see what I can come up with. And I need to finish the Windows/Mac installation steps.

I'll see what I can do in a mo (well, for Windows anyway). Today is a good day to die ... er, I mean release!

> In the remote gpio docs I've referred to the PC as the "host computer". Seeing as pigpio refers to the Pi by its "host" (IP/hostname), should we consider using another name for this?

Hmm, probably. Maybe the "executing machine"? The "machine running Python"? The "controller"? Hmm, not really enamoured of any of those. I'll keep it in mind and see if I can come up with anything better.

**Comment by bennuttall** [comment]
> I'll see what I can do in a mo (well, for Windows anyway).

I've just linked to the installing pip resource on raspberry pi learning. It's Python 3 only but that doesn't bother me. The constant "or for Python 2..." stretching out the docs really annoy me tbh. As soon as it's EOL (fingers crossed it doesn't get extended again), we should drop support. The last release before EOL will be the last release supported for Python 2.

Re: Mac, Rachel has Python 3 installed with Brew. It's 3.6 and comes with pip but her `python3` points to a different install of 3.4 and I can't seem to unlink it. I think it's safe to say if you install Python 3 with brew, you get pip. "Alternatively, install with get-pip" should be good enough.

> Hmm, probably. Maybe the "executing machine"? The "machine running Python"? The "controller"? Hmm, not really enamoured of any of those. I'll keep it in mind and see if I can come up with anything better.

It's kind of like "client" in client-server terms. Or is it server? "Master"? "Controller"?

I think host makes sense but it conflicts with the pigpio host parameter.

Perhaps something like controller, but with a note in brackets: "The controller computer (the one running the Python code)" - though some people will think of the Pi as running Python code - when it's actually not!

**Pull request merged**
